# Generated by Django 4.2.4 on 2023-08-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(blank=True, max_length=50)),
                ('E_mail', models.EmailField(max_length=50)),
                ('Address', models.TextField(max_length=100)),
                ('Create_Password', models.CharField(max_length=8)),
                ('Confirm_password', models.CharField(max_length=8)),
                ('Contact_number', models.CharField(max_length=12)),
            ],
        ),
    ]
