# Generated by Django 4.2.4 on 2023-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_clients_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.CharField(max_length=13)),
            ],
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='First_name',
            new_name='First_Name',
        ),
    ]
