# Generated by Django 4.2.4 on 2023-10-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_contact_rename_first_name_clients_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
