# Generated by Django 5.0 on 2023-12-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='uname',
        ),
    ]
