# Generated by Django 5.0 on 2024-01-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
